# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFC68J1AYBjFCihbGDfTYI395pBjVBpz
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd

df=pd.read_csv('iris.csv')

df.head(5)

df.describe()

'''
Since it is unsupervised machine learning algo,It does not consits label ouput
data,therfore we select sepal length,sepal width,petal length and petal width
as X variable.
'''

X=df.iloc[:,[0,1,2,3]].values
X[0:10]

'''
Let us consider the no of cluster is arbitaryly assig,
Say 5.
'''

from sklearn.cluster import KMeans

k5=KMeans(n_clusters=5).fit(X)
y5=k5.fit_predict(X)
y5

k5.inertia_

'''
Elbow method->which is designed to help find the optimal number
of cluster in a dataset. Here we will plot a graph between
the number of cluser and corresponding error. 
'''

error=[]
for i in range(1,11):
  k=KMeans(n_clusters=i).fit(X)
  error.append(k.inertia_)
error



import matplotlib.pyplot as plt

plt.plot(range(1,11),error)
plt.xlabel('no of cluster')
plt.ylabel('error')
plt.show()

'''
The graph show us k=3
'''

k3=KMeans(n_clusters=3)
y3=k3.fit_predict(X)
y3

plt.scatter(X[:,0],X[:,1],c=y3)
plt.show()