# -*- coding: utf-8 -*-
"""MLR_sat2pm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r7RAcKV06l9EhMV-6RZ4GYxnPLPYUt_-
"""

from google.colab import files
files.upload()

import pandas as pd
df=pd.read_csv('winequality.csv')
df.head(5) # display only first 5 rows

df.shape # no of rows and cols

df.describe() #descrine each column of the dataset of thair countinf,man,std,min value ,max value etc.

df.isnull().any() # to check whether a dataset consits null value or not

x=df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']].values

x[0:5]

y=df['quality'].values
y[0:5]

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

from sklearn.linear_model import LinearRegression
lg=LinearRegression()
lg.fit(xtrain,ytrain)

ypred=lg.predict(xtest)
df1=pd.DataFrame({'Actual':ytest,'predicted':ypred})
df1

from sklearn import metrics
metrics.mean_squared_error(ytest,ypred)