# -*- coding: utf-8 -*-
"""sat2pm_DT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X232OofquVjpXkAKh3JyQIieD-vP4IkY
"""

from google.colab import files
files.upload()



col_names=['pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']

import pandas as pd
df=pd.read_csv('pima-indians-diabetes.csv',names=col_names)
df

feature_col=['pregnant','glucose','bp','skin','insulin','bmi','pedigree','age']

x=df[feature_col]
x

y=df.label
y

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.2,random_state=1)

from sklearn.tree import DecisionTreeClassifier

cl=DecisionTreeClassifier(criterion="gini",max_depth=3)
cl.fit(xtrain,ytrain)

ypred=cl.predict(xtest)

from sklearn.metrics import confusion_matrix,accuracy_score

confusion_matrix(ytest,ypred)

accuracy_score(ytest,ypred)

from sklearn import tree

tree.plot_tree(cl)

cl1=DecisionTreeClassifier(criterion='entropy',max_depth=3)
cl1.fit(xtrain,ytrain)

ypred1=cl1.predict(xtest)

confusion_matrix(ytest,ypred1)

accuracy_score(ytest,ypred1)

tree.plot_tree(cl1)